### ISSUE TITLE
Platt Scaling for Probability Prediction

### ISSUE THREAD

**Issue by amarantolaw** [Danko-Lab/Rgtsvm#3]
Hi. This R package works wonderful. However, I wonder will there be implementation of Platt Scaling or something similar for probability prediction? As it is more convenient for some use cases. Thank you very much.

**Comment by AlexanderSchmedes** [comment]
Hey, I would also like to know if there are any plans to implement probability in this package? My current usecase is to classify oberservations into 3 classes and each period I need to assign a fixed amount of observations to class 1 and 3 and put everything else in class 2. To do this I need probabilities so that I can put the observations with the highest probabilities into class 1 and 3. Thank you.

**Comment by wzhy2000** [comment]
The multi-classification in Rgtsvm uses one-against-rest method proposed  by Crammer and Singer 2001. I have been tried to find the probability model for its prediction values. Finally I adopted the model proposed in Jonathan Milgram et al 2005 in current version. Please check whether it works for your problem:

Reference:
http://jmlr.csail.mit.edu/papers/volume2/crammer01a/crammer01a.pdf
https://www.etsmtl.ca/ETS/media/ImagesETS/Labo/LIVIA/Publications/2005/Milgram_IJCNN_2005.pdf

**Comment by wzhy2000** [comment]
The Rgtsvm also supports probability for binary classification using Platt Scaling now.
